### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by pascalg** [a-bioinformatician/BreaKmer#2]
Sorry, here is another issue:

Traceback (most recent call last):
  File "breakmer.py", line 104, in <module>
    r.run(tic)
  File "/home/pgellert/bin/BreaKmer-master/sv_processor.py", line 195, in run
    if not trgt.get_sv_reads() :
  File "/home/pgellert/bin/BreaKmer-master/sv_processor.py", line 474, in get_sv_reads
    if not self.clean_reads('sv') :
  File "/home/pgellert/bin/BreaKmer-master/sv_processor.py", line 684, in clean_reads
    self.files['%s_cleaned_fq'%type], self.cleaned_read_recs[type], self.read_len = get_fastq_reads(self.files['%s_cleaned_fq'%type], self.sv_reads[type])
  File "/home/pgellert/bin/BreaKmer-master/utils.py", line 399, in get_fastq_reads
    if add :
UnboundLocalError: local variable 'add' referenced before assignment

**Comment by ryanabo** [comment]
Thanks for reporting. Adding to the list.

**Comment by ryanabo** [comment]
This issue has been resolved in the latest release v0.0.2.
