### ISSUE TITLE
unsupported operand type

### ISSUE THREAD

**Issue by radaniba** [a-bioinformatician/BreaKmer#26]
Hello

I have one more error message from breakmer that I am reporting here

```
Traceback (most recent call last):
  File "/extscratch/apps/BreaKmer/breakmer.py", line 71, in <module>
    RUN_TRACKER = breakmer_analysis.RunTracker(params.ParamManager(PARSER.parse_args()))
  File "/extscratch/apps/BreaKmer/breakmer/params.py", line 51, in __init__
    self.set_params(arguments)
  File "/extscratch/apps/BreaKmer/breakmer/params.py", line 105, in set_params
    self.set_insertsize_thresh()  # Set the expected insert size threshold from the properly mapped read pairs.
  File "/extscratch/apps/BreaKmer/breakmer/params.py", line 263, in set_insertsize_th
resh
    isSD = utils.stddev(utils.remove_outliers(insertSizes))  # Calculate the standard deviation of the sample read pairs inser
t sizes.
  File "/extscratch/apps/BreaKmer/breakmer/utils.py", line 95, in remove_outliers
    H = 1.5 * (qnt2 - qnt1)
TypeError: unsupported operand type(s) for -: 'NoneType' and 'NoneType'
```

any ideas ?

**Comment by radaniba** [comment]
anything on this issue ?

**Comment by mducar** [comment]
Which release of Breakmer are you running?  Can you send me a copy of your config file?
