### ISSUE TITLE
pysam.sort error 

### ISSUE THREAD

**Issue by ycl6** [a-bioinformatician/BreaKmer#28]
pysam: 0.9.0
samtools: 1.3.1

```
Traceback (most recent call last):
  File "breakmer.py", line 72, in <module>
    RUN_TRACKER.run()
  File "/opt/tools/BreaKmer-0.0.7/breakmer/processor/analysis.py", line 143, in run
    aggResults = analyze_targets(targetAnalysisList)
  File "/opt/tools/BreaKmer-0.0.7/breakmer/processor/analysis.py", line 79, in analyze_targets
    if not targetRegion.find_sv_reads():  # No SV reads extracted. Exiting.
  File "/opt/tools/BreaKmer-0.0.7/breakmer/processor/target.py", line 552, in find_sv_reads
    self.extract_bam_reads('sv')  # Extract variant reads.
  File "/opt/tools/BreaKmer-0.0.7/breakmer/processor/target.py", line 578, in extract_bam_reads
    self.variation.set_var_reads(sampleType, bamFile, self.chrom, self.start, self.end, self.regionBuffer)
  File "/opt/tools/BreaKmer-0.0.7/breakmer/processor/target.py", line 165, in set_var_reads
    pysam.sort(self.files['sv_bam'], self.files['sv_bam_sorted'].replace('.bam', ''))
  File "/lib/python2.7/site-packages/pysam-0.9.0-py2.7-linux-x86_64.egg/pysam/utils.py", line 72, in __call__
    "\n".join(stderr)))
pysam.utils.SamtoolsError: 'samtools returned with error 1: stdout=, stderr=[bam_sort] Use -T PREFIX / -o FILE to specify temporary and final output files\n\nUsage: samtools sort [options...] [in.bam]\n\nOptions:\n\n  -l INT     Set compression level, from 0 (uncompressed) to 9 (best)\n\n  -m INT     Set maximum memory per thread; suffix K/M/G recognized [768M]\n\n  -n         Sort by read name\n\n  -o FILE    Write final output to FILE rather than standard output\n\n  -T PREFIX  Write temporary files to PREFIX.nnnn.bam\n\n  -@, --threads INT\n\n             Set number of sorting and compression threads [1]\n\n      --input-fmt-option OPT[=VAL]\n\n               Specify a single input file format option in the form\n\n               of OPTION or OPTION=VALUE\n\n  -O, --output-fmt FORMAT[,OPT[=VAL]]...\n\n               Specify output format (SAM, BAM, CRAM)\n\n      --output-fmt-option OPT[=VAL]\n\n               Specify a single output file format option in the form\n\n               of OPTION or OPTION=VALUE\n\n      --reference FILE\n\n               Reference sequence FASTA FILE [null]\n'
```

the `pysam.sort()` commands doesn't work with new versions of samtools, it would have to be something like this:

```
pysam.sort("-o", "reads.sorted.bam", "reads.bam")
```

So I changed the two scripts that perform sorting like below and analysis of the B2M test data can be completed finally.

breakmer/processor/target.py 

```
pysam.sort("-o", self.files['sv_bam_sorted'], self.files['sv_bam'])
```

breakmer/assembly/contig.py 

```
pysam.sort("-o", bam_out_sorted_fn, bamOutFn)
```

**Comment by mducar** [comment]
Thanks.  As noted in the ReadMe, there are a number of issues with the code currently in the master branch.  We recommend everyone use version 0.0.6.

**Comment by Shruti-Desai** [comment]
Using version 0.0.6, but still getting the same issue.

**Comment by mducar** [comment]
Shruti-Desai, can you please post the exact error message you are seeing?

In-house we are running BreaKmer using python-2.7.2 and pysam 0.7.5.  We have not tested the code with newer versions.
