### ISSUE TITLE
Issue using BreaKmer

### ISSUE THREAD

**Issue by vonholdt** [a-bioinformatician/BreaKmer#3]
Hi-

I mapped my paired end data with BWA and now would like to use BreaKmer, here is the command I'm running:

$ python <path/to/BreaKmer-master/>breakmer.py <path/to/configure/>breakmer.cfg

Traceback (most recent call last):
  File "<path/to/>BreaKmer-master/breakmer.py", line 103, in <module>
    r = runner(config_d)
  File "<path/to/>BreaKmer-master/sv_processor.py", line 100, in **init**
    self.params = params(config_d)
  File "<path/to/>BreaKmer-master/utils.py", line 705, in **init**
    self.set_params()
  File "<path/to/>BreaKmer-master/utils.py", line 792, in set_params
    self.set_targets(self.opts['gene_list'])
  File "<path/to/>BreaKmer-master/utils.py", line 769, in set_targets
    self.targets[name.upper()].append((chrm,int(bp1),int(bp2),name,feature))
ValueError: invalid literal for int() with base 10: 'M\xa5^\xb9\x97\xa8q\xd7]v1\x9a\xb7\x98\xf7>\xbd'

Can you provide advice for how I should proceed? Thank you!

**Comment by ryanabo** [comment]
This was an issue with specifying the bam file as the bed file in the configuration. This has been resolved.
