### ISSUE TITLE
NameError: global name 'sort' is not defined

### ISSUE THREAD

**Issue by Tinalxt** [a-bioinformatician/BreaKmer#34]
Hi~ I had the same problem metioned  in #30, but when I run the example_data with version 0.0.6, I got a new problem, just like below:
1 Traceback (most recent call last):
2 File "/Workspace/home/difanglei/pipeline/ctDNA/software/BreaKmer-0.0.6/breakmer.py", line 96, in 
3 r.run(tic)
4 File "/Workspace/home/difanglei/pipeline/ctDNA/software/BreaKmer-0.0.6/sv_processor.py", line 189, in run
5 trgt.extract_bam_reads() # Extract the reads that provide evidence for structural variation.
6 File "/Workspace/home/difanglei/pipeline/ctDNA/software/BreaKmer-0.0.6/sv_processor.py", line 537, in extract_bam_reads
7 sort(self.files['sv_bam'],self.files['sv_bam_sorted'].replace('.bam',''))
8 NameError: global name 'sort' is not defined
I wonder if it is a new bug? And how can I fix it. Thank you~

**Comment by GuillaumeMEXP** [comment]
Hi, 

I get the same error, did you manage to solve it ? 

Thanks !

**Comment by ryanabo** [comment]
Hello! Sorry about the troubles. This error is new to me (as the main developer) and I am wondering what version of python you are using.

**Comment by ryanabo** [comment]
Please try my branched version - https://github.com/ryanabo/BreaKmer

**Comment by GuillaumeMEXP** [comment]
Dear Ryan,


Thanks a lot for your answer !

I am using python 2.7.6.

Pysam and Biopython are uptodate.


I tried to run your Master branch but I still get an error when I prepare the data :


guillaume@guillaume-linux[venvs] python /home/guillaume/Downloads/BreaKmer-master/breakmer.py prepare_reference_data -c /home/guillaume/Documents/breakmer_test_master.cfg
Traceback (most recent call last):
  File "/home/guillaume/Downloads/BreaKmer-master/breakmer.py", line 72, in <module>
    PMANAGER = params.ParamManager(PARSER.parse_args())
  File "/home/guillaume/Downloads/BreaKmer-master/breakmer/params.py", line 49, in __init__
    self.set_params()
  File "/home/guillaume/Downloads/BreaKmer-master/breakmer/params.py", line 114, in set_params
    self.set_insertsize_thresh()  # Set the expected insert size threshold from the properly mapped read
  File "/home/guillaume/Downloads/BreaKmer-master/breakmer/params.py", line 327, in set_insertsize_thresh
    insertsize_sd = utils.stddev(utils.remove_outliers(insert_sizes))  # Calculate the standard deviation of the sample read pairs insert sizes.
  File "/home/guillaume/Downloads/BreaKmer-master/breakmer/utils.py", line 810, in remove_outliers
    intv_cut = 1.5 * (qnt2 - qnt1)
TypeError: unsupported operand type(s) for -: 'NoneType' and 'NoneType'


Do you have any idea on how to fix this problem ?


Thank you so much !


Have a nice day


Will

________________________________
De : Ryan Abo <notifications@github.com>
Envoyé : jeudi 7 décembre 2017 21:09:12
À : ccgd-profile/BreaKmer
Cc : Guillaume Dachy; Comment
Objet : Re: [ccgd-profile/BreaKmer] NameError: global name 'sort' is not defined (#34)


Please try my branched version - https://github.com/ryanabo/BreaKmer

**Comment by ryanabo** [comment]
Hi Will,

I will address this here but would appreciate if you posted the issue in the repo from which the code was downloaded. I don't get notices on this repo anymore so I could easily miss your issues. As for your current issue, I am suspecting your bam is not being read properly. Can you copy and paste a handful of the sequence reads from the bam file that are aligned? This could easily be a formatting issue and my code is not robust to it, but should be an easy fix.

Ryan

**Comment by GuillaumeMEXP** [comment]
Hi,


I made a new issue in the repo of your Master branch

https://github.com/ryanabo/BreaKmer/issues/2


There is a link to a bam file to test.


Cheers

[https://avatars2.githubusercontent.com/u/34163357?s=400&v=4]<https://github.com/ryanabo/BreaKmer/issues/2>

error prepare_reference_data · Issue #2 · ryanabo/BreaKmer<https://github.com/ryanabo/BreaKmer/issues/2>
github.com
Hi, First, thanks Ryan for this very interesting software and for the help you provide ! I tried to run your Master branch but I still get an error when I prepare the data : I am using python 2.7.6...




________________________________
De : Ryan Abo <notifications@github.com>
Envoyé : vendredi 8 décembre 2017 22:04:40
À : ccgd-profile/BreaKmer
Cc : Guillaume Dachy; Comment
Objet : Re: [ccgd-profile/BreaKmer] NameError: global name 'sort' is not defined (#34)


Hi Will,

I will address this here but would appreciate if you posted the issue in the repo from which the code was downloaded. I don't get notices on this repo anymore so I could easily miss your issues. As for your current issue, I am suspecting your bam is not being read properly. Can you copy and paste a handful of the sequence reads from the bam file that are aligned? This could easily be a formatting issue and my code is not robust to it, but should be an easy fix.

Ryan

**Comment by Myno-Jeong** [comment]
Hi.

I also had the same problem with Tinalxt.
1 Traceback (most recent call last):
2 File "/Workspace/home/difanglei/pipeline/ctDNA/software/BreaKmer-0.0.6/breakmer.py", line 96, in
3 r.run(tic)
4 File "/Workspace/home/difanglei/pipeline/ctDNA/software/BreaKmer-0.0.6/sv_processor.py", line 189, in run
5 trgt.extract_bam_reads() # Extract the reads that provide evidence for structural variation.
6 File "/Workspace/home/difanglei/pipeline/ctDNA/software/BreaKmer-0.0.6/sv_processor.py", line 537, in extract_bam_reads
7 sort(self.files['sv_bam'],self.files['sv_bam_sorted'].replace('.bam',''))
8 NameError: global name 'sort' is not defined
I sorted my bam file using gatk SortSam module.

I couldn't solve this problem.
I used BreakMer version 0.0.7 and python 2.7.6.

Would you let me know how I can solve this problem?

Many thanks,
