### ISSUE TITLE
BreaKmer - error prepare_reference_data

### ISSUE THREAD

**Issue by GuillaumeMEXP** [a-bioinformatician/BreaKmer#35]
Hello, 

I am trying to use BreaKmer to look for structural variants on Ion Ampliseq data. 
After connecting to the Blat server, I get this following error : 
```
guillaume@guillaume-linux[guillaume] python /home/guillaume/Downloads/ccgd-profile-BreaKmer-3a38315/breakmer.py prepare_reference_data -c /home/guillaume/Documents/breakmer_test.cfg 
[E::knet_seek] SEEK_END is not supported for HTTP. Offset is unchanged
[E::knet_seek] SEEK_END is not supported for HTTP. Offset is unchanged
Traceback (most recent call last):
  File "/home/guillaume/Downloads/ccgd-profile-BreaKmer-3a38315/breakmer.py", line 71, in <module>
    RUN_TRACKER = breakmer_analysis.RunTracker(params.ParamManager(PARSER.parse_args()))
  File "/home/guillaume/Downloads/ccgd-profile-BreaKmer-3a38315/breakmer/params.py", line 51, in __init__
    self.set_params(arguments)
  File "/home/guillaume/Downloads/ccgd-profile-BreaKmer-3a38315/breakmer/params.py", line 80, in set_params
    self.set_insertsize_thresh()  # Set the expected insert size threshold from the properly mapped read pairs.
  File "/home/guillaume/Downloads/ccgd-profile-BreaKmer-3a38315/breakmer/params.py", line 263, in set_insertsize_thresh
    isSD = utils.stddev(utils.remove_outliers(insertSizes))  # Calculate the standard deviation of the sample read pairs insert sizes.
  File "/home/guillaume/Downloads/ccgd-profile-BreaKmer-3a38315/breakmer/utils.py", line 95, in remove_outliers
    H = 1.5 * (qnt2 - qnt1)
TypeError: unsupported operand type(s) for -: 'NoneType' and 'NoneType'
```

I get the same error when I use a sorted or an unsorted .bam file. 

Would anyone have a precious idea ? 

Thanks a lot for your help !! 
Best,

Will

**Comment by ryanabo** [comment]
Not sure how supported this version is anymore - please try the branched version that I have worked to update: https://github.com/ryanabo/BreaKmer
