### ISSUE TITLE
installation problems

### ISSUE THREAD

**Issue by mforde84** [a-bioinformatician/BreaKmer#36]
I'm looking for some clarification on installing BreaKmer.

After running the setup script, a egg is generated in site packages which generates the following error:

python: can't find '__main__' module in '/path/to/egg/pysam-0.14-py2.7-linux-x86_64.egg'

Also the "breakmer.py" script found in the root github directory generates the following error:

> $ python breakmer.py                                                                                                                            
Traceback (most recent call last):
  File "breakmer.py", line 5, in <module>
    import breakmer.params as params
  File "/home/blik/Desktop/ccgd-profile-BreaKmer-3a38315/breakmer/params.py", line 12, in <module>
    import breakmer.utils as utils
  File "/home/blik/Desktop/ccgd-profile-BreaKmer-3a38315/breakmer/utils.py", line 12, in <module>
    from pysam import *
AttributeError: 'module' object has no attribute 'TupleProxy'

Can you please clarify how to install and run BreaKer please.

**Comment by jacquayj** [comment]
Hey @mforde84,

I figured out how to get past these issues on my MacOS 10.13.6 system. Just checkout the commit `e9effd2`. The setup.py needed a few updates for a specific `pysam` version and a missing `matplotlib` dependency. 

Here are complete instructions:

- Install latest python2.7 release
- Install virtualenv `pip2.7 install virtualenv`
- Clone repo `git clone git@github.com:ccgd-profile/BreaKmer.git`
- `cd BreaKmer`
- Checkout my branch `git checkout e9effd2`
- `python2.7 -m virtualenv env`
- `source env/bin/activate`
- `python2.7 setup.py install`

And run:

`python2.7 breakmer.py`

**Edit: It looks like the master branch is unstable, you may want to use `Breakmer_0.0.6_Profile_CCGDProduction` branch instead.**
